export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h2>Navegación</h2>
          <ul>
            <li><a href="/categorias/computadoras">Computadoras</a></li>
            <li><a href="/categorias/celulares">Celulares</a></li>
            <li><a href="/categorias/monitores">Monitores</a></li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  )
}
